#!/bin/bash

USERNAME="root"
HOSTNAMES="
fortiss-2080-ws01
"

SCRIPT="nvidia-smi --query-gpu=gpu_name,utilization.gpu,utilization.memory --format=csv,noheader"
for HOSTNAME in ${HOSTNAMES} ; do
  echo ${HOSTNAME}
  ssh -l -p 52022 ${USERNAME} ${HOSTNAME} "${SCRIPT}"
done