#!/bin/bash

USERNAME=ga63vuf
HOSTNAMES="
3090-ws01
3090-ws02
titanx-ws01
titanx-ws02
dual-2060-ws01
2060-ws01
2060-ws02
2060-ws03
2060-ws04
2060-ws05
"

# currently not reachable
# hpc07.clients.eikon.tum.de
# hpc10.clients.eikon.tum.de
# meyer.clients.ldv.ei.tum.de
# yelva.clients.ldv.ei.tum.de

# Not with a available GPU
# hpc06.clients.eikon.tum.de
# hpc08.clients.eikon.tum.de
# hpc09.clients.eikon.tum.de
# hpc10.clients.eikon.tum.de
# hpc11.clients.eikon.tum.de
# hpc12.clients.eikon.tum.de
# hpc13.clients.eikon.tum.de
# hpc14.clients.eikon.tum.de
# hpc15.clients.eikon.tum.de
# slu01.clients.eikon.tum.de
# slu02.clients.eikon.tum.de
# slu03.clients.eikon.tum.de
# fred03.clients.eikon.tum.de
# thabigt.clients.ldv.ei.tum.de

SCRIPT="nvidia-smi --query-gpu=gpu_name,utilization.gpu,utilization.memory --format=csv,noheader"
for HOSTNAME in ${HOSTNAMES} ; do
  echo ${HOSTNAME}
  ssh ${USERNAME}@${HOSTNAME} "${SCRIPT}"
done